name=CC1101_AnalogFM
version=1.0.0
author=Ashen Chathuranga
maintainer=Ashen Chathuranga
sentence=Simple analog FM transmission from incoming audio bytes with a CC1101.
paragraph=Streams 8-bit unsigned audio bytes and provides runtime carrier frequency and deviation gain control.
category=Communication
url=https://github.com/ktauchathuranga/CC1101_AnalogFM
architectures=*