name=CC1101_AnalogFM
version=1.1.1
author=Ashen Chathuranga
maintainer=Ashen Chathuranga
sentence=Simple analog FM transmission from incoming audio bytes with a CC1101.
paragraph=Streams 8-bit unsigned audio bytes and provides runtime carrier frequency and deviation gain control.
category=Communication
url=https://github.com/ktauchathuranga/cc1101-analogfm
architectures=*
